name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        u-boot-version:
          - t10n
          - t10l
          - t10n_msc0
          - t20n
          - t20l
          - t20x
          - t20n_msc0
          - t21n
          - t21n_msc0
          - t30n
          - t30l
          - t30x
          - t30a
          - t30a1
          - t30n_msc0
          - t31n
          - t31l
          - t31lc
          - t31x
          - t31a
          - t31al
          - t31n_msc0
          - t31a_msc0
          - t31al_msc0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mipsel-linux-gnu lzop u-boot-tools

      - name: u-boot-ingenic Build
        run: |
          git clone https://github.com/gtxaspec/u-boot-ingenic.git --depth 1
          cd u-boot-ingenic
          cp -f .github/scripts/u-boot-ingenic.sh u-boot-ingenic.sh
          VERSION=${{ matrix.u-boot-version }}
          bash u-boot-ingenic.sh $VERSION

      - name: Upload ${{ matrix.u-boot-version }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.TAG_NAME}}
          files: |
            u-boot-ingenic/output/u-boot-${{ matrix.u-boot-version }}-universal.bin
